# -*- mode: ruby -*-
# vi: set ft=ruby :

server_ip = "172.16.16.111"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.define "k3sserver", primary: true do |server|
    server.vm.network "private_network", ip: server_ip
    server.vm.hostname = "server"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    
  end

end
